'use strict';
// Differential test: src/lib/fscrypto.js vs ground-truth vectors generated by
// gen.py from crypto_reference.py (a Python mirror of filesender.py's
// encryption). Uses Node's real crypto.subtle (PBKDF2 + AES-GCM), so this
// exercises the exact async path the extension runs.
// Run: python3 test/crypto/gen.py && node --test test/crypto/crypto.test.js
const assert = require('node:assert/strict');
const test = require('node:test');
const fs = require('node:fs');
const path = require('node:path');

require(path.join(__dirname, '..', '..', 'src', 'lib', 'fscrypto.js'));
const FC = globalThis.fscrypto;

const V = JSON.parse(fs.readFileSync(path.join(__dirname, 'vectors.json'), 'utf8'));

function b64ToBytes(b64) {
  const bin = Buffer.from(b64, 'base64').toString('binary');
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function bytesToB64(bytes) {
  return Buffer.from(bytes).toString('base64');
}

test('file params and AES-GCM chunks match the reference', async () => {
  const p = FC.newFileParams(V.ivLength, V.size, V.chunkSize, b64ToBytes(V.ivBytes));
  assert.equal(p.ivB64, V.expectedIv, 'iv');
  assert.equal(p.aead, V.expectedAead, 'aead');

  const key = await FC.deriveKey(V.password, V.salt, V.iterations);
  for (const c of V.chunks) {
    const out = await FC.encryptChunk(key, p.ivBytes, c.index, p.aead, b64ToBytes(c.plain));
    assert.equal(bytesToB64(out), c.expected, `chunk ${c.index}`);
  }
});

test('password rules', () => {
  const rules = {
    minPasswordLength: 12,
    mixedCase: true,
    numbers: true,
    special: true,
    generatedPasswordLength: 30,
  };
  assert.equal(FC.checkPassword('Abcdefgh123!', rules).length, 0, 'a valid password passes');
  assert.ok(FC.checkPassword('Ab1!', rules).includes('length'), 'too short is flagged');
  assert.ok(
    FC.checkPassword('abcdefgh123!', rules).includes('mixedCase'),
    'missing uppercase is flagged',
  );
  assert.ok(
    FC.checkPassword('Abcdefghijk!', rules).includes('numbers'),
    'missing digit is flagged',
  );
  assert.ok(
    FC.checkPassword('Abcdefgh1234', rules).includes('special'),
    'missing special char is flagged',
  );
  assert.ok(
    FC.checkPassword('Abcdefgh123!è', rules).includes('ascii'),
    'non-ASCII char is flagged',
  );
});

test('generated passwords always satisfy the rules', () => {
  const rules = {
    minPasswordLength: 12,
    mixedCase: true,
    numbers: true,
    special: true,
    generatedPasswordLength: 30,
  };
  for (let i = 0; i < 50; i++) {
    const g = FC.generatePassword(rules);
    assert.equal(g.length, 30);
    assert.equal(FC.checkPassword(g, rules).length, 0, g);
  }
});
