'use strict';
// Differential test: src/lib/filesender.js vs ground-truth vectors generated by
// gen.py from reference.py (a Python mirror of filesender.py's call()). Uses
// Node's real crypto.subtle, so this exercises the exact async signing path the
// extension runs, not a hand-rolled substitute.
// Run: python3 test/signing/gen.py && node --test test/signing/signing.test.js
const assert = require('node:assert/strict');
const test = require('node:test');
const fs = require('node:fs');
const path = require('node:path');

require(path.join(__dirname, '..', '..', 'src', 'lib', 'filesender.js'));
const FS = globalThis.filesender;

const vectorsPath = path.join(__dirname, 'vectors.json');
const V = JSON.parse(fs.readFileSync(vectorsPath, 'utf8'));

test('signing matches the filesender.py ground truth', async (t) => {
  for (const c of V.cases) {
    await t.test(c.name, async () => {
      const opts = {
        method: c.method,
        baseUrl: V.baseUrl,
        path: c.path,
        data: c.data,
        username: V.username,
        apikey: V.apikey,
        timestamp: V.timestamp,
      };
      if (c.content !== null && c.content !== undefined) opts.content = c.content;
      if (c.rawContent !== null) opts.rawContent = FS.b64ToBytes(c.rawContent);

      const r = await FS.signedRequest(opts);
      assert.equal(FS.bytesToB64(r.signed), c.expectedSignedB64, 'signed bytes');
      assert.equal(r.signature, c.expectedSignature, 'signature');
      assert.equal(r.url, c.expectedUrl, 'url');
    });
  }
});
